server:
  port: 8080
  context-path: /vuln
  error:
    whitelabel:
      enabled: true #change to false if you want show errors


#konfiguracja z wykorzystaniem bazy danych H@

#spring:
#  datasource:
#    url: jdbc:h2:~/secure;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
#    username: app
#    password: app
#    initialize: true
#    driverClassName: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database-platform: H2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vuln_db
    username: root
    password: root
    initialize: true

    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

