server:
  port: 8085
  context-path: /vuln

spring:
  datasource:
    url: jdbc:h2:~/secure;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: app
    password: app
    initialize: true
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: H2

